# Generated by Django 5.1.4 on 2024-12-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='id',
        ),
        migrations.AlterField(
            model_name='confession',
            name='path',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
