# Generated by Django 5.1.4 on 2025-01-01 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_remove_confession_path_confession_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confession',
            name='key',
            field=models.CharField(max_length=20),
        ),
    ]
